# Generated by Django 4.2.18 on 2025-04-28 15:15

import django.contrib.auth.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Поле обязательно к заполнению.Необходимо использовать только буквы и цифры.', max_length=150, unique=True, validators=[users.validators.validate_username, users.validators.validate_username_me, django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Пользователь'),
        ),
    ]
