# Generated by Django 4.2.18 on 2025-04-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('subscribed_to')), _negated=True), name='prevent_self_subscription'),
        ),
    ]
